http://localhost:8080/api/v1/members/1
GET http://localhost:8080/api/v1/popular
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhYWFhQGdtYWlsLmNvbSI6IjExMTExMSIsImlhdCI6MTcxMzE2NzIzOCwiZXhwIjoxNzEzMjUzNjM4fQ.QWrTdNtHBRv4U-ftBZ2rSZcudCAQVnbyw_5_baj-OYQ
