GET http://localhost:8080/api/v1/popular
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0ZXN0MUBnbWFpbC5jb20iOiJ0ZXN0MSIsImlhdCI6MTcxMzUzMzYxMSwiZXhwIjoxNzEzNjIwMDExfQ.EfqHRAlZ45d8lwA309rm8aELwujOgKURmOQVWBqjL5o

GET http://localhost:8080/api/v1/communityRead/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhYWFhQGdtYWlsLmNvbSI6IjExMTExMSIsImlhdCI6MTcxMzE1OTM5MSwiZXhwIjoxNzEzMjQ1NzkxfQ.iOAG0Tbrz28KlhNb-DFow5-XoPrIDJD7TefQexFddUk